# Model Training (reference data are videos)

In [30]:
filename = 'ADTC_8_adz_raw_20260304'

In [31]:
from video_download import video_downloader

datum = video_downloader(filename)

Connection with geo-amberg.ch
Successful access to /cam/2026/03/04
ADTC Rueschlikon_00_20260304165950.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011636.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304203110.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304215925.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304215201.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304163643.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011809.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304192522.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021020.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304225913.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304205433.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015054.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020010.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020027.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304230021.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020205.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021615.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304220619.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304040001.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304225220.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304025644.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304172918.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304152314.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304182154.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304155149.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304153024.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004607.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010322.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304135245.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010638.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011514.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013406.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304195310.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010718.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304040738.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304175331.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304210722.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304180800.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304025208.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304025310.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304043720.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304203637.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013726.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304193032.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005601.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304043032.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304195326.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304033732.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021650.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304003556.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010623.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304163728.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005616.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304210604.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011724.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304014318.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304040223.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012520.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015136.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304155130.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304233657.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304032932.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013418.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010509.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021922.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005005.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304185318.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304043701.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304040634.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013130.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010157.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304193718.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304175509.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304145934.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304235248.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304191018.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004415.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015635.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304165355.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011606.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304032541.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304163011.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304162312.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005344.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304165210.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304185912.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012256.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304235917.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004550.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304135914.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304003841.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304213035.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304035300.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304173810.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020713.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005517.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304182422.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015230.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021755.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304030628.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012708.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304150721.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304023018.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021956.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304042918.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011429.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013600.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005247.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005932.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304200615.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004258.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004244.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010819.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304014121.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304222148.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013048.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304190733.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015247.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304023635.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021903.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304155336.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304170040.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304232256.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015306.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304225250.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304160015.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011851.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304014756.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020735.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005423.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304165439.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304014841.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004146.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010730.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013233.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304025352.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011140.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304185431.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005121.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304143735.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304142914.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004352.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005709.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012819.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304025610.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304033036.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304142227.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011743.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304140048.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304030740.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304014008.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004303.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304172246.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005915.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304003945.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304182213.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304182909.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304035444.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304140711.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013949.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004103.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011658.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020227.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304202906.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005500.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304183714.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013828.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304153833.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020913.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304170720.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304210019.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304022120.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304152935.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304232940.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304162920.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013022.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020844.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304150630.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304233735.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012629.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015902.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304153709.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020121.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304042409.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304223019.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013543.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010551.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304202124.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304183020.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015208.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010349.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304230735.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012022.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020944.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304195919.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304142327.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015912.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304032240.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304025059.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013713.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011445.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304180651.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021532.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304222902.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015817.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021827.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304160634.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304162453.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011836.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304212510.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021344.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015931.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304025800.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304003613.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304173055.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011942.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021325.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304150015.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304185335.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010659.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304040041.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004409.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304235133.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304042213.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304172229.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304220015.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004213.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304143620.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304023713.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012008.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020146.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304172423.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010526.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010543.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304170556.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304160818.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304213659.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012537.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015440.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304192308.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304180010.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010305.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304155905.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013548.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015947.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015843.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304215311.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304223648.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304200746.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304203723.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304014151.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304014401.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304005437.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012313.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004000.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004917.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010747.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304160801.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013220.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011535.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304192905.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304175910.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304175312.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304145351.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304003822.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304173735.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304030029.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304200026.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304135441.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013335.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304033759.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304165151.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304022008.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304205925.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304022923.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012918.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304222333.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304175450.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304014050.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304230627.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015410.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304022419.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304190028.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304020104.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304212907.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304205235.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304014751.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021810.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304162329.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304213735.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304015752.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304223758.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304010339.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013633.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021937.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304220729.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013157.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304025923.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304013403.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304004228.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304232217.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304014340.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012506.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011123.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304212229.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011655.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304143017.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304012836.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304021135.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304202429.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304011402.mp4 successfully downloaded
ADTC Rueschlikon_00_20260304145421.mp4 successfully downloaded
All videos successfully downloadeed

## DataFrame for each video (path and timestamp)

In [32]:
import os
import pandas as pd
from pathlib import Path

# change to the file directory
d = Path.cwd()
if d == Path('C:/git/RailwAI/code'):
    root = d.parent
elif d == Path('C:/git/RailwAI'):
    root = d
else:
    print('ERROR: you are actually in ' + str(Path.cwd()))

src = root / f'VIDEO/{datum}'

rows = []

for f in os.listdir(src):
    if f.endswith('.mp4'):
        file = os.path.join(src, f)
        t = f[-18:-1]
        year = t[0:4]
        month = t[4:6]
        day = t[6:8]
        hour = t[8:10]
        minute = t[10:12]
        seconde = t[12:14]

        timestamp_video = f'{year}-{month}-{day} {hour}:{minute}:{seconde}'
        
        rows.append({
            "video": file,
            "timestamp_video": pd.to_datetime(timestamp_video)
        })

df_video = pd.DataFrame(rows)
df_video.head()

                                               video     timestamp_video
0  c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon... 2026-03-04 00:35:56
1  c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon... 2026-03-04 00:36:13
2  c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon... 2026-03-04 00:38:22
3  c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon... 2026-03-04 00:38:41
4  c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon... 2026-03-04 00:39:45

In [33]:
df_train_data = pd.read_csv(f'DataFrame/df_merged_{filename}.csv')

df_video['timestamp_video'] = pd.to_datetime(df_video['timestamp_video'])
df_train_data['timestamp'] = pd.to_datetime(df_train_data['timestamp'])

df_video_merged = pd.merge_asof(
    df_video.sort_values('timestamp_video'),
    df_train_data.sort_values('timestamp'),
    left_on='timestamp_video',
    right_on='timestamp',
    direction='nearest',
    tolerance=pd.Timedelta('10s')
)

df_video_merged = df_video_merged.dropna(subset=['file'])

cols = [c for c in df_video_merged.columns if c not in ["video", "timestamp_video"]] + ["video", "timestamp_video"]
df_video_merged = df_video_merged[cols]

df_video_merged.head(5)

,file,timestamp_raw,timestamp,timestamp_serie,delta_t,velocity,length,total_length,first_peak_raw,video,timestamp_video
190,ADTC_8_adz_raw_20260304_1430,2026-03-04 14:23:16.387,2026-03-04 14:23:26.094,"[Timestamp('2026-03-04 14:23:26.094000'), Time...","[0.376, 0.137, 0.399, 0.139, 0.251, 0.131, 0.9...","[19.61236039465117, 19.752835790595576, 19.422...","[7.37424750838884, 2.706138503311594, 7.749599...",101.366520,9.929712,c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon...,2026-03-04 14:23:27
194,ADTC_8_adz_raw_20260304_1440,2026-03-04 14:37:24.352,2026-03-04 14:37:34.398,"[Timestamp('2026-03-04 14:37:34.398000'), Time...","[0.105, 0.702, 0.105, 0.199, 0.11, 0.733, 0.11...","[22.776089159067883, 22.74894290864372, 22.018...","[2.391489361702128, 15.96975792186789, 2.31197...",96.864900,9.929712,c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon...,2026-03-04 14:37:35
196,ADTC_8_adz_raw_20260304_1500,2026-03-04 14:54:10.352,2026-03-04 14:54:20.401,"[Timestamp('2026-03-04 14:54:20.401000'), Time...","[0.117, 0.78, 0.121, 0.227, 0.125, 0.813, 0.12...","[20.645256770756255, 20.494873547505122, 19.83...","[2.415495042178482, 15.986001367053996, 2.4002...",96.151421,9.929712,c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon...,2026-03-04 14:54:21
200,ADTC_8_adz_raw_20260304_1510,2026-03-04 15:07:10.432,2026-03-04 15:07:20.484,"[Timestamp('2026-03-04 15:07:20.484000'), Time...","[0.106, 0.75, 0.112, 0.215, 0.117, 0.775, 0.11...","[21.793416572077184, 21.50055991041433, 21.029...","[2.3101021566401814, 16.12541993281075, 2.3553...",96.783406,9.929712,c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon...,2026-03-04 15:07:21
201,ADTC_8_adz_raw_20260304_1530,2026-03-04 15:23:08.365,2026-03-04 15:23:18.458,"[Timestamp('2026-03-04 15:23:18.458000'), Time...","[0.118, 0.352, 0.116, 0.228, 0.108, 0.825, 0.1...","[22.38200048911714, 22.253021756647865, 22.228...","[2.6410760577158223, 7.833063658340048, 2.5784...",95.631614,9.929712,c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon...,2026-03-04 15:23:14

In [34]:
import csv
import os

# change to the file directory
d = Path.cwd()
if d == Path('C:/git/RailwAI/code'):
    root = d.parent
elif d == Path('C:/git/RailwAI'):
    root = d
else:
    print('ERROR: you are actually in ' + str(Path.cwd()))

src = root / f'VIDEO/{datum}/'

rest = []

for f in os.listdir(src):
    if f == 'reference_video.csv':
        continue
    file = os.path.join(src, f)

    if file not in df_video_merged['video'].values:
        os.remove(file)
    else:
        rest.append(file)
    
output_csv = os.path.join(src, 'reference_video.csv')

if os.path.exists(output_csv):
    print('reference_video.csv already exists')
    
else:
    with open(output_csv, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile, delimiter=';')  # use ; as separator
        writer.writerow(['video', 'train_type'])
        for vid in rest:
            writer.writerow([vid, ''])

# Manually assign the train type in the CSV file

In [35]:
d = Path.cwd()
if d == Path('C:/git/RailwAI/code'):
    root = d.parent
elif d == Path('C:/git/RailwAI'):
    root = d
else:
    print('ERROR: you are actually in ' + str(Path.cwd()))

csv_train = root / f'VIDEO/{datum}/reference_video.csv'
df_ref = pd.read_csv(csv_train, sep=';')
df_video_merged = df_video_merged.merge(df_ref, on='video', how='left')

df_video_merged.head(5)

,file,timestamp_raw,timestamp,timestamp_serie,delta_t,velocity,length,total_length,first_peak_raw,video,timestamp_video,train_type
0,ADTC_8_adz_raw_20260304_1430,2026-03-04 14:23:16.387,2026-03-04 14:23:26.094,"[Timestamp('2026-03-04 14:23:26.094000'), Time...","[0.376, 0.137, 0.399, 0.139, 0.251, 0.131, 0.9...","[19.61236039465117, 19.752835790595576, 19.422...","[7.37424750838884, 2.706138503311594, 7.749599...",101.366520,9.929712,c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon...,2026-03-04 14:23:27,DPZ
1,ADTC_8_adz_raw_20260304_1440,2026-03-04 14:37:24.352,2026-03-04 14:37:34.398,"[Timestamp('2026-03-04 14:37:34.398000'), Time...","[0.105, 0.702, 0.105, 0.199, 0.11, 0.733, 0.11...","[22.776089159067883, 22.74894290864372, 22.018...","[2.391489361702128, 15.96975792186789, 2.31197...",96.864900,9.929712,c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon...,2026-03-04 14:37:35,DTZ
2,ADTC_8_adz_raw_20260304_1500,2026-03-04 14:54:10.352,2026-03-04 14:54:20.401,"[Timestamp('2026-03-04 14:54:20.401000'), Time...","[0.117, 0.78, 0.121, 0.227, 0.125, 0.813, 0.12...","[20.645256770756255, 20.494873547505122, 19.83...","[2.415495042178482, 15.986001367053996, 2.4002...",96.151421,9.929712,c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon...,2026-03-04 14:54:21,DTZ
3,ADTC_8_adz_raw_20260304_1510,2026-03-04 15:07:10.432,2026-03-04 15:07:20.484,"[Timestamp('2026-03-04 15:07:20.484000'), Time...","[0.106, 0.75, 0.112, 0.215, 0.117, 0.775, 0.11...","[21.793416572077184, 21.50055991041433, 21.029...","[2.3101021566401814, 16.12541993281075, 2.3553...",96.783406,9.929712,c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon...,2026-03-04 15:07:21,DTZ
4,ADTC_8_adz_raw_20260304_1530,2026-03-04 15:23:08.365,2026-03-04 15:23:18.458,"[Timestamp('2026-03-04 15:23:18.458000'), Time...","[0.118, 0.352, 0.116, 0.228, 0.108, 0.825, 0.1...","[22.38200048911714, 22.253021756647865, 22.228...","[2.6410760577158223, 7.833063658340048, 2.5784...",95.631614,9.929712,c:\git\RailwAI\VIDEO\20260304\ADTC Rueschlikon...,2026-03-04 15:23:14,DPZ

In [36]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pywt
from PIL import Image

# change to the file directory
d = Path.cwd()
if d == Path('C:/git/RailwAI/code'):
    root = d.parent
elif d == Path('C:/git/RailwAI'):
    root = d
else:
    print('ERROR: you are actually in ' + str(Path.cwd()))

path = root / f'CSV_DATA/{filename}_ext'

target_length = 400
n_length = 200

for file in os.listdir(path):
    file_path = os.path.join(path, file)
    df = pd.read_csv(file_path)

    file_name = file.split('_ext')[0]
    match = df_video_merged[df_video_merged['file'] == file_name]

    if match.empty:
        print(f'No match for {file_name}')
        continue

    zugtyp = match['train_type'].iloc[0]
    if zugtyp == 'DTZ':
        classes = 'Triebzug'
    elif zugtyp == 'DPZ':
        classes = 'Lokzug'
    else:
        classes = 'Other'

    time = df['Time [s]'].values
    length = df['Length [m]'].values
    signal = df['Distance[mm]'].values

    # # shift to zero / clean the data to be sure
    # time = time - time[0]
    # length = length - length[0]
    # mask = np.isfinite(time) & np.isfinite(signal) & np.isfinite(length)

    # time = time[mask]
    # length = length[mask]
    # signal = signal[mask]

    # Downsampling - to speed up CWT
    decim = 5
    time_ds = time[::decim]
    length_ds = length[::decim]
    signal_ds = signal[::decim]

    # -------------------------------------------
    #    #######        ##      ##      ########
    #   ##              ##      ##         ##  
    #   ##              ##      ##         ##  
    #   ##              ##  ##  ##         ##
    #   ##              ##  ##  ##         ##
    #    #######         ###  ###          ## 
    # ------------------------------------------

    # Continuous Wavelet Transform
    dt = np.mean(np.diff(time_ds))                  # time step
    if not np.isfinite(dt) or dt <= 0:
        continue
    fs = 1 / dt                                     # frequency
    freqs = np.linspace(0.2, 5, 100)                # Define frequency range
    cf = pywt.central_frequency('cmor1.5-1.0')      # CWT using Morlet wavelet
    scales = cf * fs / freqs                        # convert frequency to a scale
    scales = np.clip(scales, 1, 1000)
    coeffs, _ = pywt.cwt(                           # Compute CWT
        signal_ds,
        scales,
        'cmor1.5-1.0',
        sampling_period=dt
    )
    power = np.abs(coeffs) ** 2                     # power spectrum

    # Normalize length
    length_ds = length_ds - length_ds.min()
    if length_ds.max() <= 0:
        continue
    length_ds = length_ds / length_ds.max() * target_length

    # fixed grid
    x_out = np.linspace(0, target_length, n_length) # images with 200 pixels width
    power_resampled = np.zeros((power.shape[0], n_length))
    max_len = length_ds[-1]
    max_idx = np.searchsorted(x_out, max_len)
    if max_idx < 2:
        continue

    # interpolation
    for i in range(power.shape[0]):
        power_resampled[i, :max_idx] = np.interp( # resample wavelet result
            x_out[:max_idx],
            length_ds,
            power[i, :]
        )

    # generate plots (images)
    fig, ax1 = plt.subplots(figsize=(5.12, 5.12), dpi=100)
    fig.patch.set_facecolor('white')
    ax1.set_facecolor('white')
    ax1.imshow(
        power_resampled,
        extent=[0, target_length, freqs[0], freqs[-1]],
        aspect='auto',
        cmap='Greys_r',
        origin='lower'
    )
    ax1.axis('off')
    plt.subplots_adjust(left=0, right=1, top=1, bottom=0)

    # save
    out_path = root / f'images/AI-training/{classes}'
    os.makedirs(out_path, exist_ok=True)
    out_filename = os.path.splitext(os.path.basename(file_path))[0] + ".png"
    img_path = os.path.join(out_path, out_filename)
    fig.savefig(
        img_path,
        dpi=100,
        bbox_inches='tight',
        pad_inches=0,
        facecolor='white'
    )

    # remove alpha channel (RGBA -> RGB)
    Image.open(img_path).convert('RGB').save(img_path)
    plt.close(fig)