# Model Training (reference data are videos)

In [1]:
# filename = 'ADTC_8_adz_raw_20260309'
# datum = filename.split('_')[-1]
# yy = int(datum[0:4])
# mm = int(datum[4:6])
# dd = int(datum[6:8])

# filename = 'D_05_adz_raw_20260301'
# datum = filename.split('_')[-1]
# yy = int(datum[0:4])
# mm = int(datum[4:6])
# dd = int(datum[6:8])

filename = 'ADTC1_adz_raw_20260615'

In [ ]:
from FTP.video_download import video_downloader

datum = video_downloader(filename)

Connection with geo-amberg.ch
Successful access to /cam/2026/06/15
ADTC Rastatt_00_20260615064512.mp4 successfully downloaded
ADTC Rastatt_00_20260615141717.mp4 successfully downloaded
ADTC Rastatt_00_20260615134915.mp4 successfully downloaded
ADTC Rastatt_00_20260615064704.mp4 successfully downloaded
ADTC Rastatt_00_20260615071932.mp4 successfully downloaded
ADTC Rastatt_00_20260615222518.mp4 successfully downloaded
ADTC Rastatt_00_20260615145359.mp4 successfully downloaded
ADTC Rastatt_00_20260615094443.mp4 successfully downloaded
ADTC Rastatt_00_20260615160133.mp4 successfully downloaded
ADTC Rastatt_00_20260615081709.mp4 successfully downloaded
ADTC Rastatt_00_20260615162548.mp4 successfully downloaded
ADTC Rastatt_00_20260615212052.mp4 successfully downloaded
ADTC Rastatt_00_20260615062926.mp4 successfully downloaded
ADTC Rastatt_00_20260615181659.mp4 successfully downloaded
ADTC Rastatt_00_20260615194650.mp4 successfully downloaded
ADTC Rastatt_00_20260615223227.mp4 successfully downloaded
ADTC Rastatt_00_20260615145756.mp4 successfully downloaded
ADTC Rastatt_00_20260615155231.mp4 successfully downloaded
ADTC Rastatt_00_20260615061025.mp4 successfully downloaded
ADTC Rastatt_00_20260615100833.mp4 successfully downloaded
ADTC Rastatt_00_20260615042534.mp4 successfully downloaded
ADTC Rastatt_00_20260615130246.mp4 successfully downloaded
ADTC Rastatt_00_20260615184958.mp4 successfully downloaded
ADTC Rastatt_00_20260615200519.mp4 successfully downloaded
ADTC Rastatt_00_20260615184607.mp4 successfully downloaded
ADTC Rastatt_00_20260615082505.mp4 successfully downloaded
ADTC Rastatt_00_20260615190452.mp4 successfully downloaded
ADTC Rastatt_00_20260615160545.mp4 successfully downloaded
ADTC Rastatt_00_20260615195336.mp4 successfully downloaded
ADTC Rastatt_00_20260615064303.mp4 successfully downloaded
ADTC Rastatt_00_20260615042019.mp4 successfully downloaded
ADTC Rastatt_00_20260615200501.mp4 successfully downloaded
ADTC Rastatt_00_20260615151114.mp4 successfully downloaded
ADTC Rastatt_00_20260615151358.mp4 successfully downloaded
ADTC Rastatt_00_20260615214619.mp4 successfully downloaded
ADTC Rastatt_00_20260615065313.mp4 successfully downloaded
ADTC Rastatt_00_20260615205343.mp4 successfully downloaded
ADTC Rastatt_00_20260615231124.mp4 successfully downloaded
ADTC Rastatt_00_20260615214312.mp4 successfully downloaded
ADTC Rastatt_00_20260615170106.mp4 successfully downloaded
ADTC Rastatt_00_20260615081719.mp4 successfully downloaded
ADTC Rastatt_00_20260615074626.mp4 successfully downloaded
ADTC Rastatt_00_20260615182649.mp4 successfully downloaded
ADTC Rastatt_00_20260615025316.mp4 successfully downloaded
ADTC Rastatt_00_20260615175457.mp4 successfully downloaded
ADTC Rastatt_00_20260615073109.mp4 successfully downloaded
ADTC Rastatt_00_20260615181836.mp4 successfully downloaded
ADTC Rastatt_00_20260615183357.mp4 successfully downloaded
ADTC Rastatt_00_20260615185726.mp4 successfully downloaded
ADTC Rastatt_00_20260615175122.mp4 successfully downloaded
ADTC Rastatt_00_20260615095211.mp4 successfully downloaded
ADTC Rastatt_00_20260615175924.mp4 successfully downloaded
ADTC Rastatt_00_20260615213555.mp4 successfully downloaded
ADTC Rastatt_00_20260615131901.mp4 successfully downloaded
ADTC Rastatt_00_20260615081706.mp4 successfully downloaded
ADTC Rastatt_00_20260615153523.mp4 successfully downloaded
ADTC Rastatt_00_20260615172248.mp4 successfully downloaded
ADTC Rastatt_00_20260615043000.mp4 successfully downloaded
ADTC Rastatt_00_20260615195130.mp4 successfully downloaded
ADTC Rastatt_00_20260615201221.mp4 successfully downloaded
ADTC Rastatt_00_20260615185346.mp4 successfully downloaded
ADTC Rastatt_00_20260615191346.mp4 successfully downloaded
ADTC Rastatt_00_20260615075402.mp4 successfully downloaded
ADTC Rastatt_00_20260615204842.mp4 successfully downloaded
ADTC Rastatt_00_20260615152754.mp4 successfully downloaded
ADTC Rastatt_00_20260615090225.mp4 successfully downloaded
ADTC Rastatt_00_20260615215726.mp4 successfully downloaded
ADTC Rastatt_00_20260615163418.mp4 successfully downloaded
ADTC Rastatt_00_20260615045656.mp4 successfully downloaded
ADTC Rastatt_00_20260615062044.mp4 successfully downloaded
ADTC Rastatt_00_20260615153820.mp4 successfully downloaded
ADTC Rastatt_00_20260615191421.mp4 successfully downloaded
ADTC Rastatt_00_20260615043717.mp4 successfully downloaded
ADTC Rastatt_00_20260615111102.mp4 successfully downloaded
ADTC Rastatt_00_20260615140225.mp4 successfully downloaded
ADTC Rastatt_00_20260615121404.mp4 successfully downloaded
ADTC Rastatt_00_20260615163221.mp4 successfully downloaded
ADTC Rastatt_00_20260615212946.mp4 successfully downloaded
ADTC Rastatt_00_20260615214315.mp4 successfully downloaded
ADTC Rastatt_00_20260615141938.mp4 successfully downloaded
ADTC Rastatt_00_20260615160844.mp4 successfully downloaded
ADTC Rastatt_00_20260615004017.mp4 successfully downloaded
ADTC Rastatt_00_20260615115908.mp4 successfully downloaded
ADTC Rastatt_00_20260615223120.mp4 successfully downloaded
ADTC Rastatt_00_20260615085016.mp4 successfully downloaded
ADTC Rastatt_00_20260615100259.mp4 successfully downloaded
ADTC Rastatt_00_20260615131318.mp4 successfully downloaded
ADTC Rastatt_00_20260615150200.mp4 successfully downloaded
ADTC Rastatt_00_20260615051723.mp4 successfully downloaded
ADTC Rastatt_00_20260615070554.mp4 successfully downloaded
ADTC Rastatt_00_20260615115949.mp4 successfully downloaded
ADTC Rastatt_00_20260615122706.mp4 successfully downloaded
ADTC Rastatt_00_20260615191357.mp4 successfully downloaded
ADTC Rastatt_00_20260615043714.mp4 successfully downloaded
ADTC Rastatt_00_20260615233701.mp4 successfully downloaded
ADTC Rastatt_00_20260615203129.mp4 successfully downloaded
ADTC Rastatt_00_20260615102912.mp4 successfully downloaded
ADTC Rastatt_00_20260615232959.mp4 successfully downloaded
ADTC Rastatt_00_20260615125955.mp4 successfully downloaded
ADTC Rastatt_00_20260615093429.mp4 successfully downloaded
ADTC Rastatt_00_20260615211139.mp4 successfully downloaded
ADTC Rastatt_00_20260615061638.mp4 successfully downloaded
ADTC Rastatt_00_20260615112547.mp4 successfully downloaded
ADTC Rastatt_00_20260615213143.mp4 successfully downloaded
ADTC Rastatt_00_20260615135838.mp4 successfully downloaded
ADTC Rastatt_00_20260615164327.mp4 successfully downloaded
ADTC Rastatt_00_20260615222601.mp4 successfully downloaded
ADTC Rastatt_00_20260615052055.mp4 successfully downloaded
ADTC Rastatt_00_20260615045640.mp4 successfully downloaded
ADTC Rastatt_00_20260615002742.mp4 successfully downloaded
ADTC Rastatt_00_20260615164450.mp4 successfully downloaded
ADTC Rastatt_00_20260615050214.mp4 successfully downloaded
ADTC Rastatt_00_20260615175329.mp4 successfully downloaded
ADTC Rastatt_00_20260615132632.mp4 successfully downloaded
ADTC Rastatt_00_20260615182044.mp4 successfully downloaded
ADTC Rastatt_00_20260615060252.mp4 successfully downloaded
ADTC Rastatt_00_20260615161539.mp4 successfully downloaded
ADTC Rastatt_00_20260615154812.mp4 successfully downloaded
ADTC Rastatt_00_20260615204511.mp4 successfully downloaded
ADTC Rastatt_00_20260615184236.mp4 successfully downloaded
ADTC Rastatt_00_20260615170047.mp4 successfully downloaded
ADTC Rastatt_00_20260615161038.mp4 successfully downloaded
ADTC Rastatt_00_20260615035114.mp4 successfully downloaded
ADTC Rastatt_00_20260615132947.mp4 successfully downloaded
ADTC Rastatt_00_20260615131000.mp4 successfully downloaded
ADTC Rastatt_00_20260615202824.mp4 successfully downloaded
ADTC Rastatt_00_20260615142738.mp4 successfully downloaded
ADTC Rastatt_00_20260615154229.mp4 successfully downloaded
ADTC Rastatt_00_20260615090056.mp4 successfully downloaded
ADTC Rastatt_00_20260615134816.mp4 successfully downloaded
ADTC Rastatt_00_20260615055115.mp4 successfully downloaded
ADTC Rastatt_00_20260615165516.mp4 successfully downloaded
ADTC Rastatt_00_20260615160817.mp4 successfully downloaded
ADTC Rastatt_00_20260615075432.mp4 successfully downloaded
ADTC Rastatt_00_20260615053423.mp4 successfully downloaded
ADTC Rastatt_00_20260615005417.mp4 successfully downloaded
ADTC Rastatt_00_20260615233044.mp4 successfully downloaded
ADTC Rastatt_00_20260615215016.mp4 successfully downloaded
ADTC Rastatt_00_20260615155804.mp4 successfully downloaded
ADTC Rastatt_00_20260615172500.mp4 successfully downloaded
ADTC Rastatt_00_20260615211901.mp4 successfully downloaded
ADTC Rastatt_00_20260615010142.mp4 successfully downloaded
ADTC Rastatt_00_20260615082950.mp4 successfully downloaded
ADTC Rastatt_00_20260615171642.mp4 successfully downloaded
ADTC Rastatt_00_20260615220412.mp4 successfully downloaded
ADTC Rastatt_00_20260615135202.mp4 successfully downloaded
ADTC Rastatt_00_20260615170809.mp4 successfully downloaded
ADTC Rastatt_00_20260615100414.mp4 successfully downloaded
ADTC Rastatt_00_20260615102230.mp4 successfully downloaded
ADTC Rastatt_00_20260615211625.mp4 successfully downloaded
ADTC Rastatt_00_20260615082927.mp4 successfully downloaded
ADTC Rastatt_00_20260615191847.mp4 successfully downloaded
ADTC Rastatt_00_20260615070149.mp4 successfully downloaded
ADTC Rastatt_00_20260615114251.mp4 successfully downloaded
ADTC Rastatt_00_20260615042542.mp4 successfully downloaded
ADTC Rastatt_00_20260615042033.mp4 successfully downloaded
ADTC Rastatt_00_20260615124028.mp4 successfully downloaded
ADTC Rastatt_00_20260615092500.mp4 successfully downloaded
ADTC Rastatt_00_20260615091608.mp4 successfully downloaded
ADTC Rastatt_00_20260615193542.mp4 successfully downloaded
ADTC Rastatt_00_20260615135306.mp4 successfully downloaded
ADTC Rastatt_00_20260615151017.mp4 successfully downloaded
ADTC Rastatt_00_20260615062748.mp4 successfully downloaded
ADTC Rastatt_00_20260615161435.mp4 successfully downloaded
ADTC Rastatt_00_20260615092503.mp4 successfully downloaded
ADTC Rastatt_00_20260615054029.mp4 successfully downloaded
ADTC Rastatt_00_20260615215429.mp4 successfully downloaded
ADTC Rastatt_00_20260615183938.mp4 successfully downloaded
ADTC Rastatt_00_20260615180843.mp4 successfully downloaded
ADTC Rastatt_00_20260615144224.mp4 successfully downloaded
ADTC Rastatt_00_20260615220616.mp4 successfully downloaded
ADTC Rastatt_00_20260615160405.mp4 successfully downloaded
ADTC Rastatt_00_20260615141309.mp4 successfully downloaded
ADTC Rastatt_00_20260615102055.mp4 successfully downloaded
ADTC Rastatt_00_20260615063740.mp4 successfully downloaded
ADTC Rastatt_00_20260615205153.mp4 successfully downloaded
ADTC Rastatt_00_20260615095512.mp4 successfully downloaded
ADTC Rastatt_00_20260615073300.mp4 successfully downloaded
ADTC Rastatt_00_20260615103809.mp4 successfully downloaded
ADTC Rastatt_00_20260615202457.mp4 successfully downloaded
ADTC Rastatt_00_20260615061255.mp4 successfully downloaded
ADTC Rastatt_00_20260615061304.mp4 successfully downloaded
ADTC Rastatt_00_20260615202656.mp4 successfully downloaded
ADTC Rastatt_00_20260615173645.mp4 successfully downloaded
ADTC Rastatt_00_20260615144318.mp4 successfully downloaded
ADTC Rastatt_00_20260615142330.mp4 successfully downloaded
ADTC Rastatt_00_20260615130351.mp4 successfully downloaded
ADTC Rastatt_00_20260615234029.mp4 successfully downloaded
ADTC Rastatt_00_20260615164833.mp4 successfully downloaded
ADTC Rastatt_00_20260615181157.mp4 successfully downloaded
ADTC Rastatt_00_20260615115228.mp4 successfully downloaded
ADTC Rastatt_00_20260615044100.mp4 successfully downloaded
ADTC Rastatt_00_20260615224439.mp4 successfully downloaded
ADTC Rastatt_00_20260615091103.mp4 successfully downloaded
ADTC Rastatt_00_20260615090615.mp4 successfully downloaded
ADTC Rastatt_00_20260615192858.mp4 successfully downloaded
ADTC Rastatt_00_20260615190845.mp4 successfully downloaded
ADTC Rastatt_00_20260615210849.mp4 successfully downloaded
ADTC Rastatt_00_20260615135636.mp4 successfully downloaded
ADTC Rastatt_00_20260615142231.mp4 successfully downloaded
ADTC Rastatt_00_20260615211038.mp4 successfully downloaded
ADTC Rastatt_00_20260615114722.mp4 successfully downloaded
ADTC Rastatt_00_20260615152433.mp4 successfully downloaded
ADTC Rastatt_00_20260615022732.mp4 successfully downloaded
ADTC Rastatt_00_20260615232538.mp4 successfully downloaded
ADTC Rastatt_00_20260615220629.mp4 successfully downloaded
ADTC Rastatt_00_20260615101529.mp4 successfully downloaded
ADTC Rastatt_00_20260615144902.mp4 successfully downloaded
ADTC Rastatt_00_20260615064940.mp4 successfully downloaded
ADTC Rastatt_00_20260615153948.mp4 successfully downloaded
ADTC Rastatt_00_20260615061008.mp4 successfully downloaded
ADTC Rastatt_00_20260615054743.mp4 successfully downloaded
ADTC Rastatt_00_20260615214251.mp4 successfully downloaded
ADTC Rastatt_00_20260615164706.mp4 successfully downloaded
ADTC Rastatt_00_20260615173509.mp4 successfully downloaded
ADTC Rastatt_00_20260615190425.mp4 successfully downloaded
ADTC Rastatt_00_20260615193627.mp4 successfully downloaded
ADTC Rastatt_00_20260615190125.mp4 successfully downloaded
ADTC Rastatt_00_20260615124436.mp4 successfully downloaded
ADTC Rastatt_00_20260615190048.mp4 successfully downloaded
ADTC Rastatt_00_20260615191252.mp4 successfully downloaded
ADTC Rastatt_00_20260615210505.mp4 successfully downloaded
ADTC Rastatt_00_20260615170712.mp4 successfully downloaded
ADTC Rastatt_00_20260615095919.mp4 successfully downloaded
ADTC Rastatt_00_20260615110518.mp4 successfully downloaded
ADTC Rastatt_00_20260615051253.mp4 successfully downloaded
ADTC Rastatt_00_20260615212625.mp4 successfully downloaded
ADTC Rastatt_00_20260615225430.mp4 successfully downloaded
ADTC Rastatt_00_20260615192204.mp4 successfully downloaded
ADTC Rastatt_00_20260615234053.mp4 successfully downloaded
ADTC Rastatt_00_20260615110258.mp4 successfully downloaded
ADTC Rastatt_00_20260615184057.mp4 successfully downloaded
ADTC Rastatt_00_20260615100254.mp4 successfully downloaded
ADTC Rastatt_00_20260615081620.mp4 successfully downloaded
ADTC Rastatt_00_20260615102604.mp4 successfully downloaded
ADTC Rastatt_00_20260615153243.mp4 successfully downloaded
ADTC Rastatt_00_20260615223545.mp4 successfully downloaded
ADTC Rastatt_00_20260615225319.mp4 successfully downloaded
ADTC Rastatt_00_20260615092427.mp4 successfully downloaded
ADTC Rastatt_00_20260615143241.mp4 successfully downloaded
ADTC Rastatt_00_20260615065740.mp4 successfully downloaded
ADTC Rastatt_00_20260615130627.mp4 successfully downloaded
ADTC Rastatt_00_20260615183122.mp4 successfully downloaded
ADTC Rastatt_00_20260615162009.mp4 successfully downloaded
ADTC Rastatt_00_20260615075042.mp4 successfully downloaded
ADTC Rastatt_00_20260615221633.mp4 successfully downloaded
ADTC Rastatt_00_20260615230804.mp4 successfully downloaded
ADTC Rastatt_00_20260615061621.mp4 successfully downloaded
ADTC Rastatt_00_20260615195407.mp4 successfully downloaded
ADTC Rastatt_00_20260615061428.mp4 successfully downloaded
ADTC Rastatt_00_20260615072412.mp4 successfully downloaded
ADTC Rastatt_00_20260615162443.mp4 successfully downloaded
ADTC Rastatt_00_20260615071915.mp4 successfully downloaded
ADTC Rastatt_00_20260615201838.mp4 successfully downloaded
ADTC Rastatt_00_20260615150454.mp4 successfully downloaded
ADTC Rastatt_00_20260615104300.mp4 successfully downloaded
ADTC Rastatt_00_20260615092932.mp4 successfully downloaded
ADTC Rastatt_00_20260615194002.mp4 successfully downloaded
ADTC Rastatt_00_20260615100531.mp4 successfully downloaded
ADTC Rastatt_00_20260615080815.mp4 successfully downloaded
ADTC Rastatt_00_20260615123019.mp4 successfully downloaded
ADTC Rastatt_00_20260615205841.mp4 successfully downloaded
ADTC Rastatt_00_20260615192026.mp4 successfully downloaded
ADTC Rastatt_00_20260615014209.mp4 successfully downloaded
ADTC Rastatt_00_20260615174452.mp4 successfully downloaded
ADTC Rastatt_00_20260615192520.mp4 successfully downloaded
ADTC Rastatt_00_20260615050718.mp4 successfully downloaded
ADTC Rastatt_00_20260615211606.mp4 successfully downloaded
ADTC Rastatt_00_20260615183724.mp4 successfully downloaded
ADTC Rastatt_00_20260615182341.mp4 successfully downloaded
ADTC Rastatt_00_20260615175159.mp4 successfully downloaded
ADTC Rastatt_00_20260615202233.mp4 successfully downloaded
ADTC Rastatt_00_20260615043736.mp4 successfully downloaded
ADTC Rastatt_00_20260615080524.mp4 successfully downloaded
ADTC Rastatt_00_20260615093850.mp4 successfully downloaded
ADTC Rastatt_00_20260615103315.mp4 successfully downloaded
ADTC Rastatt_00_20260615193901.mp4 successfully downloaded
ADTC Rastatt_00_20260615151749.mp4 successfully downloaded
ADTC Rastatt_00_20260615061831.mp4 successfully downloaded
ADTC Rastatt_00_20260615222101.mp4 successfully downloaded
ADTC Rastatt_00_20260615055254.mp4 successfully downloaded
ADTC Rastatt_00_20260615102029.mp4 successfully downloaded
ADTC Rastatt_00_20260615075948.mp4 successfully downloaded
ADTC Rastatt_00_20260615090409.mp4 successfully downloaded
ADTC Rastatt_00_20260615080122.mp4 successfully downloaded
ADTC Rastatt_00_20260615004000.mp4 successfully downloaded
ADTC Rastatt_00_20260615132419.mp4 successfully downloaded
ADTC Rastatt_00_20260615220050.mp4 successfully downloaded
ADTC Rastatt_00_20260615134008.mp4 successfully downloaded
ADTC Rastatt_00_20260615192346.mp4 successfully downloaded
ADTC Rastatt_00_20260615110035.mp4 successfully downloaded
ADTC Rastatt_00_20260615105105.mp4 successfully downloaded
ADTC Rastatt_00_20260615165356.mp4 successfully downloaded
ADTC Rastatt_00_20260615104749.mp4 successfully downloaded
ADTC Rastatt_00_20260615104321.mp4 successfully downloaded
ADTC Rastatt_00_20260615144640.mp4 successfully downloaded
ADTC Rastatt_00_20260615120336.mp4 successfully downloaded
ADTC Rastatt_00_20260615111425.mp4 successfully downloaded
ADTC Rastatt_00_20260615113828.mp4 successfully downloaded
ADTC Rastatt_00_20260615060136.mp4 successfully downloaded
ADTC Rastatt_00_20260615185310.mp4 successfully downloaded
ADTC Rastatt_00_20260615192651.mp4 successfully downloaded
ADTC Rastatt_00_20260615141049.mp4 successfully downloaded
ADTC Rastatt_00_20260615212520.mp4 successfully downloaded
ADTC Rastatt_00_20260615082438.mp4 successfully downloaded
ADTC Rastatt_00_20260615140848.mp4 successfully downloaded
ADTC Rastatt_00_20260615220405.mp4 successfully downloaded
ADTC Rastatt_00_20260615140039.mp4 successfully downloaded
ADTC Rastatt_00_20260615154542.mp4 successfully downloaded
ADTC Rastatt_00_20260615203250.mp4 successfully downloaded
ADTC Rastatt_00_20260615151232.mp4 successfully downloaded
ADTC Rastatt_00_20260615173756.mp4 successfully downloaded
ADTC Rastatt_00_20260615125651.mp4 successfully downloaded
ADTC Rastatt_00_20260615211615.mp4 successfully downloaded
ADTC Rastatt_00_20260615062647.mp4 successfully downloaded
ADTC Rastatt_00_20260615050747.mp4 successfully downloaded
ADTC Rastatt_00_20260615003256.mp4 successfully downloaded
All videos successfully downloadeed

## DataFrame for each video (path and timestamp)

In [3]:
import os
import pandas as pd
from pathlib import Path

# change to the file directory
d = Path.cwd()
if d == Path('C:/git/RailwAI/code'):
    root = d.parent
elif d == Path('C:/git/RailwAI'):
    root = d
else:
    print('ERROR: you are actually in ' + str(Path.cwd()))

src = root / f'VIDEO/{datum}'

rows = []

for f in os.listdir(src):
    if f.endswith('.mp4'):
        file = os.path.join(src, f)
        t = f[-18:-1]
        year = t[0:4]
        month = t[4:6]
        day = t[6:8]
        hour = t[8:10]
        minute = t[10:12]
        seconde = t[12:14]

        timestamp_video = f'{year}-{month}-{day} {hour}:{minute}:{seconde}'
        
        rows.append({
            "video": file,
            "timestamp_video": pd.to_datetime(timestamp_video)
        })

df_video = pd.DataFrame(rows)
df_video.head()

                                               video     timestamp_video
0  c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_... 2026-06-15 00:27:42
1  c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_... 2026-06-15 00:32:56
2  c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_... 2026-06-15 00:40:00
3  c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_... 2026-06-15 00:40:17
4  c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_... 2026-06-15 00:54:17

In [4]:
# df_train_data = pd.read_csv(f'DataFrame/df_merged_{filename}.csv')

# df_video['timestamp_video'] = pd.to_datetime(df_video['timestamp_video'])
# df_train_data['timestamp'] = pd.to_datetime(df_train_data['timestamp'])

# df_video_merged = pd.merge_asof(
#     df_video.sort_values('timestamp_video'),
#     df_train_data.sort_values('timestamp'),
#     left_on='timestamp_video',
#     right_on='timestamp',
#     direction='nearest',
#     tolerance=pd.Timedelta('10s')
# )

# df_video_merged = df_video_merged.dropna(subset=['file'])

# cols = [c for c in df_video_merged.columns if c not in ["video", "timestamp_video"]] + ["video", "timestamp_video"]
# df_video_merged = df_video_merged[cols]

# df_video_merged.head(5)

In [5]:
import pandas as pd

# Load data
df_train_data = pd.read_csv(f'DataFrame/df_merged_{filename}.csv')

# Convert timestamps
df_video['timestamp_video'] = pd.to_datetime(df_video['timestamp_video'])
df_train_data['timestamp'] = pd.to_datetime(df_train_data['timestamp'])

# Merge each video with the nearest train within 10 seconds
df_video_merged = pd.merge_asof(
    df_video.sort_values('timestamp_video'),
    df_train_data.sort_values('timestamp'),
    left_on='timestamp_video',
    right_on='timestamp',
    direction='nearest',
    tolerance=pd.Timedelta('10s')
)

# Remove videos with no matching train
df_video_merged = df_video_merged.dropna(subset=['file'])

# Find files with multiple videos
duplicate_counts = df_video_merged['file'].value_counts()
duplicated_files = duplicate_counts[duplicate_counts > 1]

print(f"{len(duplicated_files)} file(s) have more than one matching video.")

# Print timestamps of duplicated videos
if len(duplicated_files) > 0:
    print("\nFiles with multiple videos:")
    
    for file_name in duplicated_files.index:
        print(f"\nFile: {file_name}")
        
        videos = df_video_merged[df_video_merged['file'] == file_name]
        
        for _, row in videos.sort_values('timestamp_video').iterrows():
            print(f"  Video: {row['video']}")
            print(f"  Timestamp: {row['timestamp_video']}")

# Keep only the first video for each file
df_video_merged = (
    df_video_merged
    .sort_values('timestamp_video')
    .drop_duplicates(subset='file', keep='first')
)

# Reorder columns
cols = [c for c in df_video_merged.columns if c not in ["video", "timestamp_video"]] + ["video", "timestamp_video"]
df_video_merged = df_video_merged[cols]

# Preview
print("\nFinal dataframe:")
print(df_video_merged.head())

print(f"\nFinal number of unique files: {df_video_merged['file'].nunique()}")
print(f"Final number of rows: {len(df_video_merged)}")

5 file(s) have more than one matching video.

Files with multiple videos:

File: ADTC1_adz_raw_20260615_0614
  Video: c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_20260615061255.mp4
  Timestamp: 2026-06-15 06:12:55
  Video: c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_20260615061304.mp4
  Timestamp: 2026-06-15 06:13:04

File: ADTC1_adz_raw_20260615_1004
  Video: c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_20260615100254.mp4
  Timestamp: 2026-06-15 10:02:54
  Video: c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_20260615100259.mp4
  Timestamp: 2026-06-15 10:02:59

File: ADTC1_adz_raw_20260615_0926
  Video: c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_20260615092500.mp4
  Timestamp: 2026-06-15 09:25:00
  Video: c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_20260615092503.mp4
  Timestamp: 2026-06-15 09:25:03

File: ADTC1_adz_raw_20260615_2117
  Video: c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_20260615211606.mp4
  Timestamp: 2026-06-15 21:16:06
  Video: c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_20260615211615.mp4
  Timestamp: 2026-06-15 21:16:15

File: ADTC1_adz_raw_20260615_2205
  Video: c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_20260615220405.mp4
  Timestamp: 2026-06-15 22:04:05
  Video: c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_20260615220412.mp4
  Timestamp: 2026-06-15 22:04:12

Final dataframe:
                          file            timestamp_raw  \
0  ADTC1_adz_raw_20260615_0028  2026-06-15 00:27:32.099
1  ADTC1_adz_raw_20260615_0034  2026-06-15 00:32:46.234
2  ADTC1_adz_raw_20260615_0041  2026-06-15 00:39:50.668
4  ADTC1_adz_raw_20260615_0055  2026-06-15 00:54:06.714
5  ADTC1_adz_raw_20260615_0102  2026-06-15 01:01:32.921

                timestamp                                    timestamp_serie  \
0 2026-06-15 00:27:42.139  [Timestamp('2026-06-15 00:27:42.139000'), Time...
1 2026-06-15 00:32:56.261  [Timestamp('2026-06-15 00:32:56.261000'), Time...
2 2026-06-15 00:40:00.715  [Timestamp('2026-06-15 00:40:00.715000'), Time...
4 2026-06-15 00:54:16.755  [Timestamp('2026-06-15 00:54:16.755000'), Time...
5 2026-06-15 01:01:42.948  [Timestamp('2026-06-15 01:01:42.948000'), Time...

                                             delta_t  \
0  [0.12, 0.76, 0.12, 0.21, 0.12, 0.785, 0.117, 0...
1  [0.121, 0.37, 0.122, 0.221, 0.084, 0.344, 0.08...
2                               [0.124, 0.37, 0.124]
4    [0.105, 0.583, 0.12, 0.616, 0.12, 0.583, 0.108]
5  [0.146, 0.328, 0.144, 0.305, 0.122, 0.378, 0.118]

                                            velocity  \
0  [21.374729691864434, 21.097272270334212, 21.23...
1  [20.83643307047563, 21.136194492681717, 20.978...
2  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...
4  [22.261426993831982, 22.226805702037897, 21.67...
5  [21.088180814638804, 20.90724385451653, 21.513...

                                              length  total_length  \
0  [2.564967563023732, 16.033926925454, 2.5476062...     99.078036
1  [2.521208401527551, 7.820391962292235, 2.55937...   2925.141415
2                                    [nan, nan, nan]           NaN
4  [2.337449834352358, 12.958227724288093, 2.6006...     49.536474
5  [3.0788743989372653, 6.857575984281422, 3.0980...     32.291124

   first_peak_raw                                              video  \
0        9.922365  c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_...
1        9.917025  c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_...
2        9.936346  c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_...
4        9.931430  c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_...
5        9.912503  c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_...

      timestamp_video
0 2026-06-15 00:27:42
1 2026-06-15 00:32:56
2 2026-06-15 00:40:00
4 2026-06-15 00:54:17
5 2026-06-15 01:01:42

Final number of unique files: 122
Final number of rows: 122

In [6]:
import csv
import os

# change to the file directory
d = Path.cwd()
if d == Path('C:/git/RailwAI/code'):
    root = d.parent
elif d == Path('C:/git/RailwAI'):
    root = d
else:
    print('ERROR: you are actually in ' + str(Path.cwd()))

src = root / f'VIDEO/{datum}/'

rest = []

for f in os.listdir(src):
    if f == 'reference_video.csv':
        continue
    file = os.path.join(src, f)

    if file not in df_video_merged['video'].values:
        os.remove(file)
    else:
        rest.append(file)
    
output_csv = os.path.join(src, 'reference_video.csv')

if os.path.exists(output_csv):
    print('reference_video.csv already exists')
    
else:
    with open(output_csv, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile, delimiter=';')  # use ; as separator
        writer.writerow(['video', 'train_type'])
        for vid in rest:
            writer.writerow([vid, ''])

reference_video.csv already exists

# Manually assign the train type in the CSV file

In [7]:
d = Path.cwd()
if d == Path('C:/git/RailwAI/code'):
    root = d.parent
elif d == Path('C:/git/RailwAI'):
    root = d
else:
    print('ERROR: you are actually in ' + str(Path.cwd()))

csv_train = root / f'VIDEO/{datum}/reference_video.csv'
df_ref = pd.read_csv(csv_train, sep=';')

df_ref = df_ref.drop(
    columns=[col for col in df_ref.columns if col in df_video_merged.columns and col != 'video']
)

df_video_merged = df_video_merged.merge(
    df_ref,
    on='video',
    how='left'
)

output_dir = root / "DataframeVideo"
output_dir.mkdir(exist_ok=True)

df_video_merged.to_csv(
    output_dir / f"df_video_merged_{datum}.csv",
    index=False
)

df_video_merged.head(5)

,file,timestamp_raw,timestamp,timestamp_serie,delta_t,velocity,length,total_length,first_peak_raw,video,timestamp_video,train_type
0,ADTC1_adz_raw_20260615_0028,2026-06-15 00:27:32.099,2026-06-15 00:27:42.139,"[Timestamp('2026-06-15 00:27:42.139000'), Time...","[0.12, 0.76, 0.12, 0.21, 0.12, 0.785, 0.117, 0...","[21.374729691864434, 21.097272270334212, 21.23...","[2.564967563023732, 16.033926925454, 2.5476062...",99.078036,9.922365,c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_...,2026-06-15 00:27:42,Trieb
1,ADTC1_adz_raw_20260615_0034,2026-06-15 00:32:46.234,2026-06-15 00:32:56.261,"[Timestamp('2026-06-15 00:32:56.261000'), Time...","[0.121, 0.37, 0.122, 0.221, 0.084, 0.344, 0.08...","[20.83643307047563, 21.136194492681717, 20.978...","[2.521208401527551, 7.820391962292235, 2.55937...",2925.141415,9.917025,c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_...,2026-06-15 00:32:56,Lok
2,ADTC1_adz_raw_20260615_0041,2026-06-15 00:39:50.668,2026-06-15 00:40:00.715,"[Timestamp('2026-06-15 00:40:00.715000'), Time...","[0.124, 0.37, 0.124]","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan]",NaN,9.936346,c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_...,2026-06-15 00:40:00,Lok
3,ADTC1_adz_raw_20260615_0055,2026-06-15 00:54:06.714,2026-06-15 00:54:16.755,"[Timestamp('2026-06-15 00:54:16.755000'), Time...","[0.105, 0.583, 0.12, 0.616, 0.12, 0.583, 0.108]","[22.261426993831982, 22.226805702037897, 21.67...","[2.337449834352358, 12.958227724288093, 2.6006...",49.536474,9.931430,c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_...,2026-06-15 00:54:17,Trieb
4,ADTC1_adz_raw_20260615_0102,2026-06-15 01:01:32.921,2026-06-15 01:01:42.948,"[Timestamp('2026-06-15 01:01:42.948000'), Time...","[0.146, 0.328, 0.144, 0.305, 0.122, 0.378, 0.118]","[21.088180814638804, 20.90724385451653, 21.513...","[3.0788743989372653, 6.857575984281422, 3.0980...",32.291124,9.912503,c:\git\RailwAI\VIDEO\20260615\ADTC Rastatt_00_...,2026-06-15 01:01:42,Lok

## Inference New Data

In [17]:
from dataset import InferenceImageDataset

inference_dataset = InferenceImageDataset(
    img_dir="C:/git/RailwAI/images/inference",
    transform=transform
)

inference_dataloader = DataLoader(
    inference_dataset,
    batch_size=8,
    shuffle=False,
    num_workers=0
)

print("Inference images:", len(inference_dataset))

Inference images: 75

Load trained model

In [18]:
model.load_state_dict(
    torch.load("efficientnet_b3_traintyp.pth", map_location=device)
)

model.to(device)
model.eval()

classes = list(train_dataset.class_to_idx.keys())

Run inference

In [19]:
import pandas as pd
import torch

results = []

with torch.no_grad():
    for imgs, paths in inference_dataloader:

        imgs = imgs.to(device)

        outputs = model(imgs)

        probs = torch.softmax(outputs, dim=1)
        preds = torch.argmax(probs, dim=1)

        for path, pred, prob in zip(paths, preds, probs):

            pred_class = classes[pred.item()]
            confidence = prob[pred.item()].item() * 100

            print(f"{path} -> {pred_class}: {confidence:.2f}%")

            results.append({
                "image": path,
                "prediction": pred_class,
                "confidence": confidence
            })


df_results = pd.DataFrame(results)

df_results.to_csv(
    "inference_results.csv",
    index=False
)

df_results.head()

C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0035.png -> Lok: 99.21%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0113.png -> Trieb: 100.00%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0133.png -> Trieb: 69.56%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0151.png -> Trieb: 99.99%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0230.png -> Trieb: 98.44%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0332.png -> Trieb: 68.89%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0351.png -> Trieb: 99.85%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0431.png -> Trieb: 90.92%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0536.png -> Lok: 98.77%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0606.png -> Lok: 98.61%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0635.png -> Lok: 94.66%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0735.png -> Lok: 97.35%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0753.png -> Trieb: 98.52%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0805.png -> Lok: 97.77%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0825.png -> Trieb: 85.70%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0835.png -> Lok: 97.33%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0905.png -> Lok: 96.29%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0935.png -> Lok: 95.76%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_0955.png -> Trieb: 96.54%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1006.png -> Lok: 98.20%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1025.png -> Trieb: 98.04%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1035.png -> Lok: 98.18%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1105.png -> Lok: 98.39%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1135.png -> Lok: 94.19%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1154.png -> Trieb: 97.03%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1206.png -> Lok: 98.84%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1235.png -> Lok: 98.32%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1305.png -> Lok: 99.03%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1335.png -> Lok: 99.06%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1354.png -> Trieb: 80.13%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1405.png -> Trieb: 92.85%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1425.png -> Trieb: 98.88%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1435.png -> Lok: 95.02%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1506.png -> Lok: 96.30%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1536.png -> Lok: 95.55%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1554.png -> Lok: 53.79%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1605.png -> Lok: 98.92%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1625.png -> Trieb: 85.16%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1635.png -> Lok: 96.87%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1705.png -> Trieb: 90.24%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1735.png -> Lok: 98.98%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1755.png -> Trieb: 91.54%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1805.png -> Lok: 99.34%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1825.png -> Trieb: 96.49%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1835.png -> Lok: 98.62%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_1935.png -> Lok: 98.91%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_2005.png -> Trieb: 60.13%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_2025.png -> Trieb: 99.47%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_2035.png -> Lok: 99.21%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_2105.png -> Lok: 98.46%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_2135.png -> Lok: 98.73%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260301_2205.png -> Lok: 99.19%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_0540.png -> Lok: 95.02%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_0606.png -> Trieb: 85.83%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_0640.png -> Lok: 88.00%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_0740.png -> Lok: 70.99%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_0810.png -> Lok: 96.50%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_0840.png -> Trieb: 73.76%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_0936.png -> Lok: 96.09%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1006.png -> Lok: 93.81%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1029.png -> Trieb: 98.83%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1207.png -> Trieb: 99.26%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1225.png -> Trieb: 57.81%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1306.png -> Lok: 95.94%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1336.png -> Lok: 99.08%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1405.png -> Lok: 98.18%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1643.png -> Lok: 53.09%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1710.png -> Lok: 96.02%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1739.png -> Trieb: 99.99%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1809.png -> Lok: 88.17%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1908.png -> Lok: 95.11%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_1956.png -> Trieb: 89.85%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_2106.png -> Trieb: 99.66%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_2134.png -> Trieb: 99.59%
C:/git/RailwAI/images/inference\D_05_adz_raw_20260302_2206.png -> Lok: 98.65%

                                               image prediction  confidence
0  C:/git/RailwAI/images/inference\D_05_adz_raw_2...        Lok   99.214923
1  C:/git/RailwAI/images/inference\D_05_adz_raw_2...      Trieb  100.000000
2  C:/git/RailwAI/images/inference\D_05_adz_raw_2...      Trieb   69.556230
3  C:/git/RailwAI/images/inference\D_05_adz_raw_2...      Trieb   99.991691
4  C:/git/RailwAI/images/inference\D_05_adz_raw_2...      Trieb   98.441327